"""created paid_by, is_spend_payment_date column in Expense model

Revision ID: f68e8780e122
Revises: e1fbb086ea2c
Create Date: 2022-10-08 01:35:31.994914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f68e8780e122'
down_revision = 'e1fbb086ea2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('paid_by', sa.Enum('Bank', 'Card', 'Cash', name='paidbyenum'), nullable=False))
    op.add_column('expense', sa.Column('is_spend', sa.Boolean(), nullable=False))
    op.add_column('expense', sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expense', sa.Column("other_details", sa.String(), nullable=True))
    op.drop_column('expense', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('type', postgresql.ENUM('Bank', 'Card', 'Cash', name='paymenttypeenum'), autoincrement=False, nullable=False))
    op.drop_column('expense', 'other_details')
    op.drop_column('expense', 'payment_date')
    op.drop_column('expense', 'is_spend')
    op.drop_column('expense', 'paid_by')
    # ### end Alembic commands ###
